// This file is auto-generated by prelude-generator. Do not edit.

pub # [doc = " This module implements \"drop bombs\" intended for use by command wrappers to ensure that the"] # [doc = " constructed commands are *eventually* executed. This is exactly like `rustc_errors::Diag` where"] # [doc = " we force every `Diag` to be consumed or we emit a bug, but we panic instead."] # [doc = ""] # [doc = " This is adapted from <https://docs.rs/drop_bomb/latest/drop_bomb/> and simplified for our"] # [doc = " purposes."] use std :: ffi :: { OsStr , OsString } ;
pub use crate :: prelude :: * ;
pub use serde_derive :: { Deserialize , Serialize } ;
pub use std :: collections :: BTreeMap ;
pub use std :: fs :: File ;
pub use std :: io :: { BufRead , BufReader } ;
pub use std :: panic ;
pub use std :: path :: Path ;
pub use std :: path :: { Path , PathBuf } ;
pub use std :: process :: Command ;
pub use std :: process :: { Command , Stdio } ;
pub use std :: sync :: OnceLock ;
pub use super :: DropBomb ;
