use crate::prelude::*


use bootstrap_config_builder::config::AppConfig;
use bootstrap_config_builder::args::Args;
use bootstrap_config_builder::utils::format_file;
use std::path::PathBuf;

#[test]
fn test_app_config_deserialization() {
    let toml_content = r#"##
        stage = "test_stage"
        target = "test_target"
        project_root = "/test/project_root"
        system = "test_system"
        output = "/test/output"
        rust_bootstrap_nix_flake_ref = "test_bootstrap_ref"
        rust_src_flake_ref = "test_src_ref"
        nixpkgs_path = "/test/nixpkgs"
        rust_overlay_path = "/test/rust_overlay"
        rust_bootstrap_nix_path = "/test/bootstrap_nix_path"
        configuration_nix_path = "/test/config_nix_path"
        rust_src_flake_path = "/test/rust_src_path"
        dry_run = true
        rustc_path = "/test/rustc"
        cargo_path = "/test/cargo"
        rust_channel = "nightly"
        rust_download_rustc = true
        rust_parallel_compiler = true
        rust_llvm_tools = true
        rust_debuginfo_level = 2
        patch_binaries_for_nix = true
        vendor = true
        build_dir = "/test/build_dir"
        build_jobs = 8
        home_dir = "/test/home"
        cargo_home_dir = "/test/cargo_home"
        install_prefix = "/test/install_prefix"
        install_sysconfdir = "/test/install_sysconfdir"
        dist_sign_folder = "/test/dist_sign_folder"
        dist_upload_addr = "test_upload_addr"
        llvm_download_ci_llvm = true
        llvm_ninja = true
        change_id = "test_change_id"
    "#;

    let config: AppConfig = toml::from_str(toml_content).unwrap();

    assert_eq!(config.stage, Some("test_stage".to_string()));
    assert_eq!(config.target, Some("test_target".to_string()));
    assert_eq!(config.project_root, Some(PathBuf::from("/test/project_root")));
    assert_eq!(config.system, Some("test_system".to_string()));
    assert_eq!(config.output, Some(PathBuf::from("/test/output")));
    assert_eq!(config.rust_bootstrap_nix_flake_ref, Some("test_bootstrap_ref".to_string()));
    assert_eq!(config.rust_src_flake_ref, Some("test_src_ref".to_string()));
    assert_eq!(config.nixpkgs_path, Some(PathBuf::from("/test/nixpkgs")));
    assert_eq!(config.rust_overlay_path, Some(PathBuf::from("/test/rust_overlay")));
    assert_eq!(config.rust_bootstrap_nix_path, Some(PathBuf::from("/test/bootstrap_nix_path")));
    assert_eq!(config.configuration_nix_path, Some(PathBuf::from("/test/config_nix_path")));
    assert_eq!(config.rust_src_flake_path, Some(PathBuf::from("/test/rust_src_path")));
    assert_eq!(config.dry_run, Some(true));
    assert_eq!(config.rustc_path, Some(PathBuf::from("/test/rustc")));
    assert_eq!(config.cargo_path, Some(PathBuf::from("/test/cargo")));
    assert_eq!(config.rust_channel, Some("nightly".to_string()));
    assert_eq!(config.rust_download_rustc, Some(true));
    assert_eq!(config.rust_parallel_compiler, Some(true));
    assert_eq!(config.rust_llvm_tools, Some(true));
    assert_eq!(config.rust_debuginfo_level, Some(2));
    assert_eq!(config.patch_binaries_for_nix, Some(true));
    assert_eq!(config.vendor, Some(true));
    assert_eq!(config.build_dir, Some(PathBuf::from("/test/build_dir")));
    assert_eq!(config.build_jobs, Some(8));
    assert_eq!(config.home_dir, Some(PathBuf::from("/test/home")));
    assert_eq!(config.cargo_home_dir, Some(PathBuf::from("/test/cargo_home")));
    assert_eq!(config.install_prefix, Some(PathBuf::from("/test/install_prefix")));
    assert_eq!(config.install_sysconfdir, Some(PathBuf::from("/test/install_sysconfdir")));
    assert_eq!(config.dist_sign_folder, Some(PathBuf::from("/test/dist_sign_folder")));
    assert_eq!(config.dist_upload_addr, Some("test_upload_addr".to_string()));
    assert_eq!(config.llvm_download_ci_llvm, Some(true));
    assert_eq!(config.llvm_ninja, Some(true));
    assert_eq!(config.change_id, Some("test_change_id".to_string()));
}

#[test]
fn test_app_config_merge_with_args() {
    let mut config = AppConfig {
        stage: Some("initial_stage".to_string()),
        target: Some("initial_target".to_string()),
        rustc_path: Some(PathBuf::from("/initial/rustc")),
        ..Default::default()
    };

    let args = Args {
        stage: Some("arg_stage".to_string()),
        rustc_path: Some(PathBuf::from("/arg/rustc")),
        vendor: Some(true),
        ..Default::default()
    };

    config.merge_with_args(&args);

    assert_eq!(config.stage, Some("arg_stage".to_string()));
    assert_eq!(config.target, Some("initial_target".to_string())); // Should remain unchanged
    assert_eq!(config.rustc_path, Some(PathBuf::from("/arg/rustc")));
    assert_eq!(config.vendor, Some(true));
}

#[test]
fn test_format_file_all_placeholders() {
    let template_content = r#"##
# Generated by bootstrap-config-builder
#
# System: {system}
# Project Root: {flake_path_str}

[nix]
nixpkgs_path = "{nixpkgs_path}"
rust_overlay_path = "{rust_overlay_path}"
rust_bootstrap_nix_path = "{rust_bootstrap_nix_path}"
configuration_nix_path = "{configuration_nix_path}"
rust_src_flake_path = "{rust_src_flake_path}"
rust_bootstrap_nix_flake_ref = "{rust_bootstrap_nix_flake_ref}"
rust_src_flake_ref = "{rust_src_flake_ref}"

[rust]
rustc = "{rustc_path}"
cargo = "{cargo_path}"
channel = "{rust_channel}"
download-rustc = {rust_download_rustc}
parallel-compiler = {rust_parallel_compiler}
llvm-tools = {rust_llvm_tools}
debuginfo-level = {rust_debuginfo_level}

[build]
stage = {stage}
target = "{target}"
patch-binaries-for-nix = {patch_binaries_for_nix}
vendor = {vendor}
build-dir = "{build_dir}"
jobs = {build_jobs}

[env]
HOME = "{home_dir}"
CARGO_HOME = "{cargo_home_dir}"

[install]
prefix = "{install_prefix}"
sysconfdir = "{install_sysconfdir}"

[dist]
sign-folder = "{dist_sign_folder}"
upload-addr = "{dist_upload_addr}"

[llvm]
download-ci-llvm = {llvm_download_ci_llvm}
ninja = {llvm_ninja}

[change-id]
id = "{change_id}"
    "#;

    // Create a dummy example.toml file for the test
    let temp_dir = tempfile::tempdir().unwrap();
    let template_path = temp_dir.path().join("example.toml");
    std::fs::write(&template_path, template_content).unwrap();

    let result = format_file::format_file(
        template_path.to_str().unwrap(),
        "test_system",
        "/test/flake_path",
        "/test/nixpkgs",
        "/test/rust_overlay",
        "/test/bootstrap_nix_path",
        "/test/config_nix_path",
        "/test/rust_src_path",
        "test_bootstrap_ref",
        "test_src_ref",
        "1",
        "x86_64-unknown-linux-gnu",
        "/test/rustc",
        "/test/cargo",
        "stable",
        false,
        true,
        false,
        1,
        true,
        false,
        "/test/build_dir",
        4,
        "/test/home",
        "/test/cargo_home",
        "/test/install_prefix",
        "/test/install_sysconfdir",
        "/test/dist_sign_folder",
        "test_upload_addr",
        false,
        true,
        "test_change_id",
    );

    assert!(result.contains("System: test_system"));
    assert!(result.contains("Project Root: /test/flake_path"));
    assert!(result.contains("nixpkgs_path = \"/test/nixpkgs\""));
    assert!(result.contains("rust_overlay_path = \"/test/rust_overlay\""));
    assert!(result.contains("rust_bootstrap_nix_path = \"/test/bootstrap_nix_path\""));
    assert!(result.contains("configuration_nix_path = \"/test/config_nix_path\""));
    assert!(result.contains("rust_src_flake_path = \"/test/rust_src_path\""));
    assert!(result.contains("rust_bootstrap_nix_flake_ref = \"test_bootstrap_ref\""));
    assert!(result.contains("rust_src_flake_ref = \"test_src_ref\""));
    assert!(result.contains("stage = 1"));
    assert!(result.contains("target = \"x86_64-unknown-linux-gnu\""));
    assert!(result.contains("rustc = \"/test/rustc\""));
    assert!(result.contains("cargo = \"/test/cargo\""));
    assert!(result.contains("channel = \"stable\""));
    assert!(result.contains("download-rustc = false"));
    assert!(result.contains("parallel-compiler = true"));
    assert!(result.contains("llvm-tools = false"));
    assert!(result.contains("debuginfo-level = 1"));
    assert!(result.contains("patch-binaries-for-nix = true"));
    assert!(result.contains("vendor = false"));
    assert!(result.contains("build-dir = \"/test/build_dir\""));
    assert!(result.contains("jobs = 4"));
    assert!(result.contains("HOME = \"/test/home\""));
    assert!(result.contains("CARGO_HOME = \"/test/cargo_home\""));
    assert!(result.contains("prefix = \"/test/install_prefix\""));
    assert!(result.contains("sysconfdir = \"/test/install_sysconfdir\""));
    assert!(result.contains("sign-folder = \"/test/dist_sign_folder\""));
    assert!(result.contains("upload-addr = \"test_upload_addr\""));
    assert!(result.contains("download-ci-llvm = false"));
    assert!(result.contains("ninja = true"));
    assert!(result.contains("id = \"test_change_id\""));
}
