//! This file was automatically generated by a refactoring script.
//! It contains the definition of `distdir` from `dist.rs`.

pub(crate) fn distdir(builder: &Builder<'_>) -> PathBuf {
    builder.out.join("dist")
}
