use crate::prelude::*;


//! This file was automatically generated by a refactoring script.
//! It contains the definition of `pkgname` from `dist.rs`.

pub fn pkgname(builder: &Builder<'_>, component: &str) -> String {
    format!("{}-{}", component, builder.rust_package_vers())
}
