use crate::prelude::*


//! This file was automatically generated by a refactoring script.
//! It contains the definition of `should_build_extended_tool` from `dist.rs`.

fn should_build_extended_tool(builder: &Builder<'_>, tool: &str) -> bool {
    if !builder.config.extended {
        return false;
    }
    builder.config.tools.as_ref().map_or(true, |tools| tools.contains(tool))
}
