use crate::prelude::*;


//! This file was automatically generated by a refactoring script.
//! It contains the definition of `skip_host_target_lib` from `dist.rs`.

fn skip_host_target_lib(builder: &Builder<'_>, compiler: Compiler) -> bool {
    // The only true set of target libraries came from the build triple, so
    // let's reduce redundant work by only producing archives from that host.
    if compiler.host != builder.config.build {
        builder.info("	skipping, not a build host");
        true
    } else {
        false
    }
}

