//! This file was automatically generated by a refactoring script.
//! It contains the definition of `tmpdir` from `dist.rs`.

pub fn tmpdir(builder: &Builder<'_>) -> PathBuf {
    builder.out.join("tmp/dist")
}
