#!/usr/bin/env bash

# --- Configuration and Argument Parsing ---

DRY_RUN=false
if [ "$1" = "--dry-run" ]; then
    DRY_RUN=true
    echo "--- Running in Dry Run Mode ---"
fi

# This script performs three main tasks:
# 1. It ensures that any 'use crate::prelude::*' statements in Rust files are correctly terminated with a semicolon.
# 2. It automatically generates a 'prelude.rs' file for each Cargo crate in the project.
# 3. It generates a single 'project_prelude.rs' file at the root, containing all unique 'use' statements from the entire project.

# --- Task 1: Fix missing semicolons in prelude imports ---

echo "Checking for missing semicolons in prelude imports..."
PRELUDE_LINE="use crate::prelude::*";
FILES_TO_FIX=$(grep -r -l "${PRELUDE_LINE}" --include "*.rs" . | xargs grep -L "${PRELUDE_LINE};" --include "*.rs")

if [ -n "$FILES_TO_FIX" ]; then
    for file in $FILES_TO_FIX;
    do
        if [ "$DRY_RUN" = "true" ]; then
            echo "[DRY RUN] Would add semicolon to prelude in $file"
        else
            echo "Adding semicolon to prelude in $file"
            sed -i '/use crate::prelude::*$/s/$/;/' "$file"
        fi
    done
else
    echo "No missing semicolons found."
fi
echo "Prelude semicolon fix complete."
echo "---"


# --- Task 2: Generate prelude.rs for each crate ---

echo "Generating prelude files for all crates..."
GLOBAL_PRELUDE_TEMP_FILE=$(mktemp)

# Find all Cargo.toml files, which mark the root of a crate.
find . -name "Cargo.toml" -print0 | while IFS= read -r -d $'' cargo_toml; do
    crate_dir=$(dirname "$cargo_toml")
    src_dir="$crate_dir/src"

    if [ -d "$src_dir" ]; then
        echo "Processing crate: $crate_dir"

        use_statements=$(grep -h -r --include "*.rs" -E '^\s*use ' "$src_dir" |
            grep -v '^\s*//' |
            sort -u)

        if [ -n "$use_statements" ]; then
            # Append to global prelude temp file
            echo "$use_statements" >> "$GLOBAL_PRELUDE_TEMP_FILE"

            prelude_file="$src_dir/prelude.rs"
            
            if [ "$DRY_RUN" = "true" ]; then
                echo "[DRY RUN] Would generate prelude file: $prelude_file"
            else
                echo "  -> Generating prelude file: $prelude_file"
                {
                    echo "// This file is auto-generated by 'ensure_prelude_rust.sh'. Do not edit."
                    echo ""
                } > "$prelude_file"

                echo "$use_statements" | while IFS= read -r use_line; do
                    if [[ "$use_line" != *";" ]]; then
                        use_line="${use_line};";
                    fi
                    echo "pub ${use_line}" >> "$prelude_file"
                done
            fi

            crate_root_lib="$src_dir/lib.rs"
            crate_root_main="$src_dir/main.rs"
            crate_root=""

            if [ -f "$crate_root_lib" ]; then
                crate_root="$crate_root_lib"
            elif [ -f "$crate_root_main" ]; then
                crate_root="$crate_root_main"
            fi

            if [ -n "$crate_root" ]; then
                if ! grep -q "pub mod prelude;" "$crate_root"; then
                    if [ "$DRY_RUN" = "true" ]; then
                        echo "[DRY RUN] Would add 'pub mod prelude;' to $crate_root"
                    else
                        echo "  -> Adding 'pub mod prelude;' to $crate_root"
                        awk 'NR==1 && /^#\!/ {print; print "\npub mod prelude;"; next} NR==1 {print "pub mod prelude;";} 1' "$crate_root" > "$crate_root.tmp" && mv "$crate_root.tmp" "$crate_root"
                    fi
                fi
            fi
        else
            echo "  -> No 'use' statements found to generate a prelude."
        fi
    fi
done

echo "Per-crate prelude generation complete."
echo "---"

# --- Task 3: Generate global prelude ---

echo "Generating global project prelude..."
GLOBAL_PRELUDE_FILE="project_prelude.rs"

unique_global_uses=$(sort -u "$GLOBAL_PRELUDE_TEMP_FILE")
rm "$GLOBAL_PRELUDE_TEMP_FILE"

if [ "$DRY_RUN" = "true" ]; then
    echo "[DRY RUN] Would generate global prelude file: $GLOBAL_PRELUDE_FILE"
else
    echo "  -> Generating global prelude file: $GLOBAL_PRELUDE_FILE"
    {
        echo "// This file is auto-generated by 'ensure_prelude_rust.sh'. Do not edit."
        echo "// It contains all unique 'use' statements from across the entire project."
        echo ""
    } > "$GLOBAL_PRELUDE_FILE"

    echo "$unique_global_uses" | while IFS= read -r use_line; do
        if [[ "$use_line" != *";" ]]; then
            use_line="${use_line};";
        fi
        echo "pub ${use_line}" >> "$GLOBAL_PRELUDE_FILE"
    done
fi

echo "Global prelude generation complete."