// Generated by Gemini CLI
// Do not edit manually

pub trait CommandMY_LOCAL_SCRIPT_SHTrait {
    fn execute(&self, args: &[&str]) -> Result<String, String>;
}

pub trait CommandLSTrait {
    fn execute(&self, args: &[&str]) -> Result<String, String>;
}


