use crate::prelude::*


use super::format_file; // Import from sibling module

#[allow(clippy::too_many_arguments)]
pub fn construct_config_content(
    system: &str,
    flake_path_str: &str,
    nixpkgs_path: &str,
    rust_overlay_path: &str,
    rust_bootstrap_nix_path: &str,
    configuration_nix_path: &str,
    rust_src_flake_path: &str,
    stage: &str,
    target: &str,
    rust_bootstrap_nix_flake_ref: &str,
    rust_src_flake_ref: &str,
    rustc_path: &str,
    cargo_path: &str,
    rust_channel: &str,
    rust_download_rustc: bool,
    rust_parallel_compiler: bool,
    rust_llvm_tools: bool,
    rust_debuginfo_level: u8,
    patch_binaries_for_nix: bool,
    vendor: bool,
    build_dir: &str,
    build_jobs: u32,
    home_dir: &str,
    cargo_home_dir: &str,
    install_prefix: &str,
    install_sysconfdir: &str,
    dist_sign_folder: &str,
    dist_upload_addr: &str,
    llvm_download_ci_llvm: bool,
    llvm_ninja: bool,
    change_id: &str,
) -> String {
    format_file::format_file(
        system,
        flake_path_str,
        nixpkgs_path,
        rust_overlay_path,
        rust_bootstrap_nix_path,
        configuration_nix_path,
        rust_src_flake_path,
        rust_bootstrap_nix_flake_ref,
        rust_src_flake_ref,
        stage,
        target,
        rustc_path,
        cargo_path,
        rust_channel,
        rust_download_rustc,
        rust_parallel_compiler,
        rust_llvm_tools,
        rust_debuginfo_level,
        patch_binaries_for_nix,
        vendor,
        build_dir,
        build_jobs,
        home_dir,
        cargo_home_dir,
        install_prefix,
        install_sysconfdir,
        dist_sign_folder,
        dist_upload_addr,
        llvm_download_ci_llvm,
        llvm_ninja,
        change_id
    )
}