// use anyhow::{Context, Result}; // Commented out
use std::fs;

#[allow(clippy::too_many_arguments)]
pub fn format_file(
    system: &str,
    flake_path_str: &str,
    nixpkgs_path: &str,
    rust_overlay_path: &str,
    rust_bootstrap_nix_path: &str,
    configuration_nix_path: &str,
    rust_src_flake_path: &str,
    rust_bootstrap_nix_flake_ref: &str,
    rust_src_flake_ref: &str,
    stage: &str,
    target: &str,
    rustc_path: &str,
    cargo_path: &str,
    rust_channel: &str,
    rust_download_rustc: bool,
    rust_parallel_compiler: bool,
    rust_llvm_tools: bool,
    rust_debuginfo_level: u8,
    patch_binaries_for_nix: bool,
    vendor: bool,
    build_dir: &str,
    build_jobs: u32,
    home_dir: &str,
    cargo_home_dir: &str,
    install_prefix: &str,
    install_sysconfdir: &str,
    dist_sign_folder: &str,
    dist_upload_addr: &str,
    llvm_download_ci_llvm: bool,
    llvm_ninja: bool,
    change_id: &str,
) -> String {
    let template_content = r#"# Generated by bootstrap-config-builder
#
# System: {system}
# Project Root: {flake_path_str}

[nix]
nixpkgs_path = "{nixpkgs_path}"
rust_overlay_path = "{rust_overlay_path}"
rust_bootstrap_nix_path = "{rust_bootstrap_nix_path}"
configuration_nix_path = "{configuration_nix_path}"
rust_src_flake_path = "{rust_src_flake_path}"
rust_bootstrap_nix_flake_ref = "{rust_bootstrap_nix_flake_ref}"
rust_src_flake_ref = "{rust_src_flake_ref}"

[rust]
rustc = "{rustc_path}"
cargo = "{cargo_path}"
channel = "{rust_channel}"
download-rustc = {rust_download_rustc}
parallel-compiler = {rust_parallel_compiler}
llvm-tools = {rust_llvm_tools}
debuginfo-level = {rust_debuginfo_level}

[build]
stage = {stage}
target = "{target}"
patch-binaries-for-nix = {patch_binaries_for_nix}
vendor = {vendor}
build-dir = "{build_dir}"
jobs = {build_jobs}

[env]
HOME = "{home_dir}"
CARGO_HOME = "{cargo_home_dir}"

[install]
prefix = "{install_prefix}"
sysconfdir = "{install_sysconfdir}"

[dist]
sign-folder = "{dist_sign_folder}"
upload-addr = "{dist_upload_addr}"

[llvm]
download-ci-llvm = {llvm_download_ci_llvm}
ninja = {llvm_ninja}

# Example for target-specific configurations
# [target.{target_triple}]
# cc = "{target_cc}"
# android-ndk = "{target_android_ndk}"

[change-id]
id = "{change_id}"
"#;

    // Use string replacement for each placeholder
    template_content
        .replace("{system}", system)
        .replace("{flake_path_str}", flake_path_str)
        .replace("{nixpkgs_path}", nixpkgs_path)
        .replace("{rust_overlay_path}", rust_overlay_path)
        .replace("{rust_bootstrap_nix_path}", rust_bootstrap_nix_path)
        .replace("{configuration_nix_path}", configuration_nix_path)
        .replace("{rust_src_flake_path}", rust_src_flake_path)
        .replace("{rust_bootstrap_nix_flake_ref}", rust_bootstrap_nix_flake_ref)
        .replace("{rust_src_flake_ref}", rust_src_flake_ref)
        .replace("{stage}", stage)
        .replace("{target}", target)
        .replace("{rustc_path}", rustc_path)
        .replace("{cargo_path}", cargo_path)
        .replace("{rust_channel}", rust_channel)
        .replace("{rust_download_rustc}", &rust_download_rustc.to_string())
        .replace("{rust_parallel_compiler}", &rust_parallel_compiler.to_string())
        .replace("{rust_llvm_tools}", &rust_llvm_tools.to_string())
        .replace("{rust_debuginfo_level}", &rust_debuginfo_level.to_string())
        .replace("{patch_binaries_for_nix}", &patch_binaries_for_nix.to_string())
        .replace("{vendor}", &vendor.to_string())
        .replace("{build_dir}", build_dir)
        .replace("{build_jobs}", &build_jobs.to_string())
        .replace("{home_dir}", home_dir)
        .replace("{cargo_home_dir}", cargo_home_dir)
        .replace("{install_prefix}", install_prefix)
        .replace("{install_sysconfdir}", install_sysconfdir)
        .replace("{dist_sign_folder}", dist_sign_folder)
        .replace("{dist_upload_addr}", dist_upload_addr)
        .replace("{llvm_download_ci_llvm}", &llvm_download_ci_llvm.to_string())
        .replace("{llvm_ninja}", &llvm_ninja.to_string())
        .replace("{change_id}", change_id)
}
