// This file is automatically generated by project-generator from /data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/platform-tools-agave-rust-solana/vendor/rust-src/vendor/rust/rust-bootstrap-nix/generated-declarations-lib/src/handle_collect_and_process_use_statements.rs.
// Do not modify this file directly.



use build_helper::prelude::*;

pub mod handle_collect_and_process_use_statements;
