// configuration-nix/src/config_generator.rs

use crate::config_params::ConfigParams;
use std::fs;

pub fn generate_config_toml(params: &ConfigParams) {

    // Construct config.toml content
    let config_content = format!(
        r###"# Generated by configuration-nix

[nix]
nixpkgs_path = "{}"
rust_overlay_path = "{}"
configuration_nix_path = "{}"
rust_src_flake_path = "{}"

[build]
stage = {}
target = "{}"
"###,
        params.nixpkgs_path.to_string_lossy(),
        params.rust_overlay_path.to_string_lossy(),
        params.configuration_nix_path.to_string_lossy(),
        params.rust_src_flake_path.to_string_lossy(),
        params.stage,
        params.target
    );

    let config_file_path = "config.toml".to_string();
    fs::write(&config_file_path, config_content).unwrap();
}
