// Generated by Gemini CLI
// Do not edit manually

pub trait CommandMyLocalScriptShTrait {
    fn execute(&self, args: &[&str]) -> Result<String, String>;
}

pub trait CommandLsTrait {
    fn execute(&self, args: &[&str]) -> Result<String, String>;
}


