//! This file was automatically generated by a refactoring script.
//! It now imports modules containing definitions extracted from the original file.

use std::borrow::Cow;
use std::collections::HashSet;
use std::ffi::OsStr;
use std::io::BufReader;
use std::io::prelude::*;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::{env, fs, str};

use serde_derive::Deserialize;

use crate::core::build_steps::tool::SourceType;
use crate::core::build_steps::{dist, llvm};
use crate::core::builder;
use crate::core::builder::{
    Builder, Cargo, Kind, PathSet, RunConfig, ShouldRun, Step, TaskPath, crate_description,
};
use crate::core::config::{DebuginfoLevel, LlvmLibunwind, RustcLto, TargetSelection};
use crate::utils::exec::command;
use crate::utils::helpers::{
    exe, get_clang_cl_resource_dir, is_debug_info, is_dylib, symlink_dir, t, up_to_date,
};
use crate::{CLang, Compiler, DependencyType, GitRepo, LLVM_TOOLS, Mode};

// --- Extracted Modules ---
pub mod std;
mod copy_and_stamp;
mod copy_llvm_libunwind;
mod copy_third_party_objects;
mod copy_self_contained_objects;
pub mod std_crates_for_run_make;
mod compiler_rt_for_profiler;
pub mod std_cargo;
mod std_link;
mod copy_sanitizers;
mod apple_darwin_update_library_name;
mod apple_darwin_sign_file;
pub mod startup_objects;
mod cp_rustc_component_to_ci_sysroot;
pub mod rustc;
pub mod rustc_cargo;
pub mod rustc_cargo_env;
mod rustc_llvm_env;
mod rustc_link;
pub mod codegen_backend;
mod needs_codegen_config;
mod is_codegen_cfg_needed;
mod copy_codegen_backends_to_sysroot;
pub mod libstd_stamp;
pub mod librustc_stamp;
mod codegen_backend_stamp;
pub mod compiler_file;
pub mod sysroot;
pub mod assemble;
pub mod add_to_sysroot;
pub mod run_cargo;
pub mod stream_cargo;
pub mod cargo_target;
pub mod cargo_message;
pub mod strip_debug;

// --- Remaining top-level items ---
pub(crate) const CODEGEN_BACKEND_PREFIX: &str = "rustc_codegen_";
