use crate::prelude::*;
use serde_derive::Deserialize;
#[derive(Debug, Default, Deserialize)]
#[derive(Clone)]
pub struct LocalLlvm {
    pub optimize: Option<bool>,
    pub thin_lto: Option<bool>,
    pub release_debuginfo: Option<bool>,
    pub assertions: Option<bool>,
    pub tests: Option<bool>,
    pub enzyme: Option<bool>,
    pub plugins: Option<bool>,
    pub ccache: Option<String>,
    pub static_libstdcpp: Option<bool>,
    pub libzstd: Option<bool>,
    pub ninja: Option<bool>,
    pub targets: Option<Vec<String>>,
    pub experimental_targets: Option<Vec<String>>,
    pub link_jobs: Option<usize>,
    pub link_shared: Option<bool>,
    pub version_suffix: Option<String>,
    pub clang_cl: Option<String>,
    pub cflags: Option<String>,
    pub cxxflags: Option<String>,
    pub ldflags: Option<String>,
    pub use_libcxx: Option<bool>,
    pub use_linker: Option<String>,
    pub allow_old_toolchain: Option<bool>,
    pub offload: Option<bool>,
    pub polly: Option<bool>,
    pub clang: Option<bool>,
    pub enable_warnings: Option<bool>,
    pub download_ci_llvm: Option<bool>,
    pub build_config: Option<String>,
    pub enable_projects: Option<Vec<String>>,
}
