

use serde_derive::Deserialize;

#[derive(Debug, Default, Deserialize)]
#[derive(Clone)]
pub struct LocalBuild {
    pub build: Option<String>,
    pub host: Option<Vec<String>>,
    pub target: Option<Vec<String>>,
    pub build_dir: Option<std::path::PathBuf>,
    pub cargo: Option<std::path::PathBuf>,
    pub rustc: Option<std::path::PathBuf>,
    pub rustfmt: Option<std::path::PathBuf>,
    pub cargo_clippy: Option<bool>,
    pub docs: Option<bool>,
    pub compiler_docs: Option<bool>,
    pub library_docs_private_items: Option<bool>,
    pub docs_minification: Option<bool>,
    pub submodules: Option<bool>,
    pub gdb: Option<std::path::PathBuf>,
    pub lldb: Option<std::path::PathBuf>,
    pub nodejs: Option<std::path::PathBuf>,
    pub npm: Option<std::path::PathBuf>,
    pub python: Option<std::path::PathBuf>,
    pub reuse: Option<std::path::PathBuf>,
    pub locked_deps: Option<bool>,
    pub vendor: Option<bool>,
    pub full_bootstrap: Option<bool>,
    pub bootstrap_cache_path: Option<std::path::PathBuf>,
    pub extended: Option<bool>,
    pub tools: Option<Vec<String>>,
    pub verbose: Option<usize>,
    pub sanitizers: Option<bool>,
    pub profiler: Option<bool>,
    pub cargo_native_static: Option<bool>,
    pub low_priority: Option<bool>,
    pub configure_args: Option<Vec<String>>,
    pub local_rebuild: Option<bool>,
    pub print_step_timings: Option<bool>,
    pub print_step_rusage: Option<bool>,
    pub check_stage: Option<usize>,
    pub doc_stage: Option<usize>,
    pub build_stage: Option<usize>,
    pub test_stage: Option<usize>,
    pub install_stage: Option<usize>,
    pub dist_stage: Option<usize>,
    pub bench_stage: Option<usize>,
    pub patch_binaries_for_nix: Option<bool>,
    pub metrics: Option<bool>,
    pub android_ndk: Option<std::path::PathBuf>,
    pub optimized_compiler_builtins: Option<bool>,
    pub jobs: Option<usize>,
    pub compiletest_diff_tool: Option<String>,
    pub src: Option<std::path::PathBuf>,
}
