[package]
name = "rust-system-composer"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-submodule-tool-lib = { workspace = true, optional = true }
cargo-repo-sync-lib = { workspace = true, optional = true }
git2 = { version = "*", optional = true }
hex = { version = "*", optional = true }
cargo_metadata = { workspace = true, optional = true }
sha1 = { version = "*", optional = true }
pathdiff = { version = "*", optional = true }
git-wrapper-lib = { workspace = true, optional = true }
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
toml_edit = "0.22"
config = "0.13"
walkdir = "2.0"
fs_extra = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
prelude-generator = { path = "../prelude-generator" }
cargo-flake-generator = { path = "../tools/cargo-flake-generator" }
flake-template-generator = { path = "../flake-template-generator" }
split-expanded-lib = { path = "../split-expanded-lib" }
expanded-code-collector = { path = "../crates/expanded-code-collector" }
code-graph-flattener = { path = "../crates/code-graph-flattener" }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"


[features]
cargo_submodule_tool_lib_enabled = ["dep:cargo-submodule-tool-lib"]
syn_enabled = ["dep:syn"]
toml_edit_enabled = ["dep:toml_edit"]
clap_enabled = ["dep:clap"]
cargo_repo_sync_lib_enabled = ["dep:cargo-repo-sync-lib"]
git2_enabled = ["dep:git2"]
hex_enabled = ["dep:hex"]
cargo_metadata_enabled = ["dep:cargo_metadata"]
sha1_enabled = ["dep:sha1"]
anyhow_enabled = ["dep:anyhow"]
pathdiff_enabled = ["dep:pathdiff"]
serde_enabled = ["dep:serde"]
serde_json_enabled = ["dep:serde_json"]
walkdir_enabled = ["dep:walkdir"]
git_wrapper_lib_enabled = ["dep:git-wrapper-lib"]

