//! This file was automatically generated by a refactoring script.
//! It contains the definition of `apple_darwin_sign_file` from `compile.rs`.

fn apple_darwin_sign_file(builder: &Builder<'_>, file_path: &Path) {
    command("codesign")
        .arg("-f") // Force to rewrite the existing signature
        .arg("-s")
        .arg("-")
        .arg(file_path)
        .run(builder);
}
