use crate::prelude::*;


//! This file was automatically generated by a refactoring script.
//! It contains the definition of `apple_darwin_update_library_name` from `compile.rs`.

fn apple_darwin_update_library_name(builder: &Builder<'_>, library_path: &Path, new_name: &str) {
    command("install_name_tool").arg("-id").arg(new_name).arg(library_path).run(builder);
}
