use crate::prelude::*;


/// This file was automatically generated by a refactoring script.
/// It contains the definition of `CargoMessage` from `compile.rs`.

#[derive(Deserialize)]
#[serde(tag = "reason", rename_all = "kebab-case")]
pub enum CargoMessage<'a> {
    CompilerArtifact { filenames: Vec<Cow<'a, str>>, target: CargoTarget<'a> },
    BuildScriptExecuted,
    BuildFinished,
}
