use serde::{Deserialize, Serialize};


/// This file was automatically generated by a refactoring script.
/// It contains the definition of `CargoTarget` from `compile.rs`.

#[derive(Deserialize)]
pub struct CargoTarget<'a> {
    crate_types: Vec<Cow<'a, str>>,
}
