use crate::prelude::*;


/// This file was automatically generated by a refactoring script.
/// It contains the definition of `compiler_file` from `compile.rs`.

pub fn compiler_file(
    builder: &Builder<'_>,
    compiler: &Path,
    target: TargetSelection,
    c: CLang,
    file: &str,
) -> PathBuf {
    if builder.config.dry_run {
        return PathBuf::new();
    }
    let mut cmd = command(compiler);
    cmd.args(builder.cflags(target, GitRepo::Rustc, c));
    cmd.arg(format!("-print-file-name={file}"));
    let out = cmd.run_capture_stdout(builder).stdout();
    PathBuf::from(out.trim())
}
