use crate::prelude::*


//! This file was automatically generated by a refactoring script.
//! It contains the definition of `copy_and_stamp` from `compile.rs`.

fn copy_and_stamp(
    builder: &Builder<'_>,
    libdir: &Path,
    sourcedir: &Path,
    name: &str,
    target_deps: &mut Vec<(PathBuf, DependencyType)>,
    dependency_type: DependencyType,
) {
    let target = libdir.join(name);
    builder.copy_link(&sourcedir.join(name), &target);

    target_deps.push((target, dependency_type));
}
