use crate::prelude::*;


/// This file was automatically generated by a refactoring script.
/// It contains the definition of `librustc_stamp` from `compile.rs`.

/// Cargo's output path for librustc in a given stage, compiled by a particular
/// compiler for the specified target.
pub fn librustc_stamp(
    builder: &Builder<'_>,
    compiler: Compiler,
    target: TargetSelection,
) -> PathBuf {
    builder.cargo_out(compiler, Mode::Rustc, target).join(".librustc.stamp")
}
