use crate::prelude::*;


/// This file was automatically generated by a refactoring script.
/// It contains the definition of `libstd_stamp` from `compile.rs`.

/// Cargo's output path for the standard library in a given stage, compiled
/// by a particular compiler for the specified target.
pub fn libstd_stamp(builder: &Builder<'_>, compiler: Compiler, target: TargetSelection) -> PathBuf {
    builder.cargo_out(compiler, Mode::Std, target).join(".libstd.stamp")
}
