// This file is automatically generated by project-generator from /data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/platform-tools-agave-rust-solana/vendor/rust-src/vendor/rust/rust-bootstrap-nix/generated-declarations-lib/src/unknown_declaration.rs.
// Do not modify this file directly.


extern crate openssl_sys;

use build_helper::prelude::*;

