.PHONY: run-nix-dir

run-nix-dir:
	nix develop /data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/platform-tools-agave-rust-solana/vendor/rust-src/vendor/rust/rust-bootstrap-nix --command cargo run --bin nix-dir