#!/usr/bin/env bash

generate_lib_rs() {
    local LIB_ROOT_DIR="$1"
    local LIB_DIR="${LIB_ROOT_DIR}/src"
    local LIB_RS="${LIB_DIR}/lib.rs"

    # Clear existing lib.rs content
    > "${LIB_RS}"

    # Add a header to lib.rs
    echo "// This file is automatically generated by generate_lib_rs.sh" >> "${LIB_RS}"
    echo "// Do not modify this file directly." >> "${LIB_RS}"
    echo "" >> "${LIB_RS}"

    # Iterate over all .rs files in the directory and add pub mod statements
    for file in "${LIB_DIR}"/*.rs; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            mod_name=$(echo "$filename" | sed 's/\.rs$//')
            if [ "$mod_name" = "_" ]; then
                mod_name="UNDERSCORE"
            fi
            # Exclude lib.rs itself from being mod-ed
            if [ "$mod_name" != "lib" ]; then
                echo "pub mod ${mod_name};" >> "${LIB_RS}"
            fi
        fi
    done

    echo "Generated ${LIB_RS} with pub mod statements."
}

# Call the function for generated-declarations-lib
generate_lib_rs "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/platform-tools-agave-rust-solana/vendor/rust-src/vendor/rust/rust-bootstrap-nix/generated-declarations-lib"

# Call the function for generated-proc-macros-lib
generate_lib_rs "/data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/platform-tools-agave-rust-solana/vendor/rust-src/vendor/rust/rust-bootstrap-nix/generated-proc-macros-lib"