// This file is automatically generated by project-generator.
// Do not modify this file directly.


use anyhow::{Context, Result};
use std::process::Command;
use clap::{Args, Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::{Path, PathBuf};


