// This file is automatically generated by project-generator from /data/data/com.termux.nix/files/home/pick-up-nix2/vendor/rust/platform-tools-agave-rust-solana/vendor/rust-src/vendor/rust/rust-bootstrap-nix/generated-declarations-lib/src/write_string_constants_to_hierarchical_structure.rs.
// Do not modify this file directly.



use build_helper::prelude::*;

pub mod write_string_constants_to_hierarchical_structure;
