// This file is auto-generated by prelude-generator. Do not edit.

pub use quote :: quote ;
pub use std :: { env , fs , io , path :: { Path , PathBuf } } ;
pub use syn :: { self , Item , Ident , spanned :: Spanned } ;
pub use walkdir :: WalkDir ;
